### ISSUE TITLE
Cant find devices

### ISSUE THREAD

**Issue by TheRealTsevenXD** [GeekyEggo/GoveeController#37]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

its about the H6143

### Bug Description

![Screenshot 2023-01-17 175157](https://user-images.githubusercontent.com/61120738/212961450-241b7782-c223-416c-bda8-a5fed26b1590.png)
So this is the only thing that pop up after i entered the api.

### Logs

```bash
2023-01-17 17:47:06.0683 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-01-17 17:47:06.1022 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:47:06.1022 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:47:06.7031 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 590.5233ms - 429
2023-01-17 17:47:06.7031 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 610.772ms - 429
2023-01-17 17:47:06.7157 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: TooManyRequests {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2023-01-17 17:48:26.7115 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-01-17 17:48:26.7115 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:48:26.7115 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:48:27.2315 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 519.8309ms - 429
2023-01-17 17:48:27.2315 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 519.9574ms - 429
2023-01-17 17:48:27.2315 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: TooManyRequests {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2023-01-17 17:48:30.0239 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-01-17 17:48:30.0239 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-01-17 17:48:30.0239 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:48:30.0239 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:48:30.1472 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 123.1928ms - 429
2023-01-17 17:48:30.1472 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 123.2892ms - 429
2023-01-17 17:48:30.1472 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: TooManyRequests {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2023-01-17 17:48:35.9382 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-01-17 17:48:35.9382 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-01-17 17:48:35.9382 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:48:35.9382 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:48:36.0588 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 120.468ms - 429
2023-01-17 17:48:36.0588 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 120.5866ms - 429
2023-01-17 17:48:36.0588 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: TooManyRequests {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2023-01-17 17:49:07.5995 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-01-17 17:49:07.6459 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:49:07.6459 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:49:08.2488 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 592.4474ms - 429
2023-01-17 17:49:08.2488 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 613.8063ms - 429
2023-01-17 17:49:08.2613 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: TooManyRequests {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2023-01-17 17:50:06.7692 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-01-17 17:50:06.7692 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:50:06.7692 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:50:06.8920 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 122.5707ms - 429
2023-01-17 17:50:06.8920 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 122.6974ms - 429
2023-01-17 17:50:06.8920 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: TooManyRequests {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
2023-01-17 17:50:09.8025 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 218
2023-01-17 17:50:10.3010 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 218
2023-01-17 17:50:10.6320 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 218
2023-01-17 17:50:10.8687 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 218
2023-01-17 17:50:11.2735 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 218
2023-01-17 17:50:12.0907 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 218
2023-01-17 17:50:15.6617 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-01-17 17:50:15.6617 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-01-17 17:50:15.6617 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:50:15.6617 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-01-17 17:50:15.7838 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 121.7503ms - 429
2023-01-17 17:50:15.7838 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 121.9035ms - 429
2023-01-17 17:50:15.7838 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: TooManyRequests {"message":"rate limited! the limit is 10000 requests every 24 hours. X-RateLimit-Reset in Http Response Header shows the reset time."}
```

**Comment by GeekyEggo** [comment]
Hey @TheRealTsevenXD, could I ask you to try with the latest beta version; it includes a lot of HTTP improvements, which will hopefully resolve this issue. It can be [downloaded directly from here](https://github.com/GeekyEggo/GoveeController/raw/main/dist/com.geekyeggo.goveecontroller.streamDeckPlugin).

**Comment by TheRealTsevenXD** [comment]
That worked Thank you so much, also great plugin. Needed this for so long!!!

**Comment by GeekyEggo** [comment]
That’s awesome news, and thank you for the kind words. 💖 I’m going to close this issue, but if you encounter any problems in the future, please let me know.
