### ISSUE TITLE
Govee stream deck not detecting device

### ISSUE THREAD

**Issue by KingstonXyz** [GeekyEggo/GoveeController#43]
### Pre-Checks

- [X] The device is connected to WiFi.
- [X] The device is supported by [Govees API](https://govee-public.s3.amazonaws.com/developer-docs/GoveeAPIReference.pdf).

### Operating System

Windows

### Govee Device

Product model: H6126
RGB lightstrips

### Bug Description

![ss](https://user-images.githubusercontent.com/127925771/225225468-c4bf5baf-2706-435c-b292-aca06fb08c5b.JPG)

When I try to select my H6126 LED light strips under the device portion of the on/off Govee button nothing pops up on the drop-down under "devices" This happens every time I try and select a device to turn on/off, I have also tested the other buttons to see if the device just doesn't pop up for the on/off but there is nothing for the other buttons under the "devices" drop down.

### Logs

```bash
2023-03-14 23:11:48.4831 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:11:50.2050 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:11:52.7654 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:11:54.1040 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:11:54.1236 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:11:54.1291 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:02.0970 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 7961.6979ms - 200
2023-03-14 23:12:02.0970 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 7985.2301ms - 200
2023-03-14 23:12:02.1104 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:02.1412 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:02.1412 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:02.1412 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:02.1412 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:02.1412 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:02.2019 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 60.4277ms - 200
2023-03-14 23:12:02.2019 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 60.5103ms - 200
2023-03-14 23:12:02.2019 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:02.2019 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:06.5956 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:06.5956 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:06.5956 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:06.5956 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:06.6621 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 66.3922ms - 200
2023-03-14 23:12:06.6621 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 66.4734ms - 200
2023-03-14 23:12:06.6621 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:06.6621 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:20.0556 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:20.0556 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:20.0556 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:20.0556 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:20.1273 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 71.6741ms - 200
2023-03-14 23:12:20.1273 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 71.7459ms - 200
2023-03-14 23:12:20.1273 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:20.1273 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:20.1933 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:20.1933 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:20.1933 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:20.1933 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:20.2679 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 74.5659ms - 200
2023-03-14 23:12:20.2679 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 74.6256ms - 200
2023-03-14 23:12:20.2679 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:20.2679 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:21.2915 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:21.2915 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:21.2915 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:21.2915 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:21.3653 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 73.7652ms - 200
2023-03-14 23:12:21.3653 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 73.821ms - 200
2023-03-14 23:12:21.3653 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:21.3653 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:21.7256 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:21.7256 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:21.7256 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:21.7256 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:21.8066 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 80.9046ms - 200
2023-03-14 23:12:21.8066 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 80.9683ms - 200
2023-03-14 23:12:21.8066 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:21.8066 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:21.8735 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:21.8735 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:21.8735 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:21.8735 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:21.9456 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 72.0019ms - 200
2023-03-14 23:12:21.9456 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 72.0517ms - 200
2023-03-14 23:12:21.9456 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:21.9456 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:22.0237 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:22.0237 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:22.0237 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:22.0237 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:22.1002 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 76.462ms - 200
2023-03-14 23:12:22.1002 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 76.5114ms - 200
2023-03-14 23:12:22.1002 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:22.1002 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:12:22.1794 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:12:22.1794 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:12:22.1794 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:22.1794 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:12:22.2512 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 71.7065ms - 200
2023-03-14 23:12:22.2512 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 71.7706ms - 200
2023-03-14 23:12:22.2512 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:12:22.2512 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:13:15.3459 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:13:15.3459 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:13:15.3459 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:13:15.3459 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:13:15.4198 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 73.7426ms - 200
2023-03-14 23:13:15.4198 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 73.7991ms - 200
2023-03-14 23:13:15.4198 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:13:15.4198 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:13:28.7729 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 227
2023-03-14 23:24:00.5921 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:24:00.5921 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:24:00.5921 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:24:00.5921 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:24:00.8168 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 224.3114ms - 200
2023-03-14 23:24:00.8168 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 224.3883ms - 200
2023-03-14 23:24:00.8168 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:24:00.8168 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:25:11.8060 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 227
2023-03-14 23:25:16.9795 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:25:16.9795 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:25:16.9795 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:25:16.9795 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:25:17.2322 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 252.596ms - 200
2023-03-14 23:25:17.2322 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 252.6443ms - 200
2023-03-14 23:25:17.2322 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:25:17.2322 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:26:13.0015 [DEBUG] GoveeController.Govee.GoveeService: Invalidating device cache.
2023-03-14 23:26:13.0015 [DEBUG] GoveeController.Govee.GoveeService: Getting devices from API.
2023-03-14 23:26:13.0015 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: Start processing HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:26:13.0015 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Sending HTTP request GET https://developer-api.govee.com/v1/devices/
2023-03-14 23:26:13.3249 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.ClientHandler: Received HTTP response headers after 323.1933ms - 200
2023-03-14 23:26:13.3249 [INFO] System.Net.Http.HttpClient.GoveeHttpClient.LogicalHandler: End processing HTTP request after 323.2458ms - 200
2023-03-14 23:26:13.3249 [DEBUG] GoveeController.Govee.GoveeHttpClient: Communicating with Govee...
Request: GET https://developer-api.govee.com/v1/devices/
Response: OK {"code":200,"message":"success","data":{}}
2023-03-14 23:26:13.3249 [DEBUG] GoveeController.Govee.GoveeService: Updated device list cache.
2023-03-14 23:30:08.3451 [ERROR] SharpDeck.Connectivity.StreamDeckActionRegistry: Failed to invoke action "com.geekyeggo.goveecontroller.turnonoff".
System.ArgumentNullException: Device identifier cannot be null. (Parameter 'deviceId')
   at GoveeController.Govee.GoveeService.GetDeviceInfoAsync(String deviceId, CancellationToken cancellationToken) in C:\git\GoveeController\src\GoveeController\Govee\GoveeService.cs:line 81
   at GoveeController.Actions.TurnOnOffAction.OnKeyDown(ActionEventArgs`1 args) in C:\git\GoveeController\src\GoveeController\Actions\TurnOnOffAction.cs:line 23
   at SharpDeck.Connectivity.StreamDeckActionRegistry.<>c__DisplayClass32_0`1.<<InvokeOnActionAsync>b__0>d.MoveNext() in C:\git\SharpDeck\src\SharpDeck\Connectivity\StreamDeckActionRegistry.cs:line 227
```

**Comment by GeekyEggo** [comment]
Hey @KingstonXyz, sadly H6126 isn’t supported as part of [Govee’s public API documentation](https://govee-public.s3.amazonaws.com/developer-docs/GoveeDeveloperAPIReference.pdf); without API support, the plug-in won’t be able to control the device.
